<?php

declare(strict_types=1);

/*
 * PaybullLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaybullLib\Models;

use stdClass;

class GetTokenRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $appId;

    /**
     * @var string
     */
    private $appSecret;

    /**
     * @param string $appId
     * @param string $appSecret
     */
    public function __construct(string $appId, string $appSecret)
    {
        $this->appId = $appId;
        $this->appSecret = $appSecret;
    }

    /**
     * Returns App Id.
     */
    public function getAppId(): string
    {
        return $this->appId;
    }

    /**
     * Sets App Id.
     *
     * @required
     * @maps app_id
     */
    public function setAppId(string $appId): void
    {
        $this->appId = $appId;
    }

    /**
     * Returns App Secret.
     */
    public function getAppSecret(): string
    {
        return $this->appSecret;
    }

    /**
     * Sets App Secret.
     *
     * @required
     * @maps app_secret
     */
    public function setAppSecret(string $appSecret): void
    {
        $this->appSecret = $appSecret;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['app_id']     = $this->appId;
        $json['app_secret'] = $this->appSecret;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
