<?php

declare(strict_types=1);

/*
 * PaybullLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaybullLib\Models;

use stdClass;

class InstallementRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $creditCard;

    /**
     * @var string
     */
    private $amount;

    /**
     * @var string
     */
    private $currencyCode;

    /**
     * @var string
     */
    private $merchantKey;

    /**
     * @var int
     */
    private $is2d;

    /**
     * @param string $creditCard
     * @param string $amount
     * @param string $currencyCode
     * @param string $merchantKey
     * @param int $is2d
     */
    public function __construct(
        string $creditCard,
        string $amount,
        string $currencyCode,
        string $merchantKey,
        int $is2d
    ) {
        $this->creditCard = $creditCard;
        $this->amount = $amount;
        $this->currencyCode = $currencyCode;
        $this->merchantKey = $merchantKey;
        $this->is2d = $is2d;
    }

    /**
     * Returns Credit Card.
     */
    public function getCreditCard(): string
    {
        return $this->creditCard;
    }

    /**
     * Sets Credit Card.
     *
     * @required
     * @maps credit_card
     */
    public function setCreditCard(string $creditCard): void
    {
        $this->creditCard = $creditCard;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Currency Code.
     */
    public function getCurrencyCode(): string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     *
     * @required
     * @maps currency_code
     */
    public function setCurrencyCode(string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Merchant Key.
     */
    public function getMerchantKey(): string
    {
        return $this->merchantKey;
    }

    /**
     * Sets Merchant Key.
     *
     * @required
     * @maps merchant_key
     */
    public function setMerchantKey(string $merchantKey): void
    {
        $this->merchantKey = $merchantKey;
    }

    /**
     * Returns Is 2 D.
     */
    public function getIs2d(): int
    {
        return $this->is2d;
    }

    /**
     * Sets Is 2 D.
     *
     * @required
     * @maps is_2d
     */
    public function setIs2d(int $is2d): void
    {
        $this->is2d = $is2d;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['credit_card']   = $this->creditCard;
        $json['amount']        = $this->amount;
        $json['currency_code'] = $this->currencyCode;
        $json['merchant_key']  = $this->merchantKey;
        $json['is_2d']         = $this->is2d;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
