<?php

declare(strict_types=1);

/*
 * PaybullLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaybullLib\Models;

use stdClass;

class MerchantActiveInstallementsRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $merchantKey;

    /**
     * @param string $merchantKey
     */
    public function __construct(string $merchantKey)
    {
        $this->merchantKey = $merchantKey;
    }

    /**
     * Returns Merchant Key.
     */
    public function getMerchantKey(): string
    {
        return $this->merchantKey;
    }

    /**
     * Sets Merchant Key.
     *
     * @required
     * @maps merchant_key
     */
    public function setMerchantKey(string $merchantKey): void
    {
        $this->merchantKey = $merchantKey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['merchant_key'] = $this->merchantKey;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
