<?php

declare(strict_types=1);

/*
 * PaybullLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaybullLib\Models;

use stdClass;

class OrderStatusBrandedRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $merchantKey;

    /**
     * @var string
     */
    private $invoiceId;

    /**
     * @var int
     */
    private $isDirectBank;

    /**
     * @param string $merchantKey
     * @param string $invoiceId
     * @param int $isDirectBank
     */
    public function __construct(string $merchantKey, string $invoiceId, int $isDirectBank)
    {
        $this->merchantKey = $merchantKey;
        $this->invoiceId = $invoiceId;
        $this->isDirectBank = $isDirectBank;
    }

    /**
     * Returns Merchant Key.
     */
    public function getMerchantKey(): string
    {
        return $this->merchantKey;
    }

    /**
     * Sets Merchant Key.
     *
     * @required
     * @maps merchant_key
     */
    public function setMerchantKey(string $merchantKey): void
    {
        $this->merchantKey = $merchantKey;
    }

    /**
     * Returns Invoice Id.
     */
    public function getInvoiceId(): string
    {
        return $this->invoiceId;
    }

    /**
     * Sets Invoice Id.
     *
     * @required
     * @maps invoice_id
     */
    public function setInvoiceId(string $invoiceId): void
    {
        $this->invoiceId = $invoiceId;
    }

    /**
     * Returns Is Direct Bank.
     */
    public function getIsDirectBank(): int
    {
        return $this->isDirectBank;
    }

    /**
     * Sets Is Direct Bank.
     *
     * @required
     * @maps is_direct_bank
     */
    public function setIsDirectBank(int $isDirectBank): void
    {
        $this->isDirectBank = $isDirectBank;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['merchant_key']   = $this->merchantKey;
        $json['invoice_id']     = $this->invoiceId;
        $json['is_direct_bank'] = $this->isDirectBank;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
