<?php

declare(strict_types=1);

/*
 * PaybullLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaybullLib\Models;

use stdClass;

class PreauthConfirmPaymentAPIRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $invoiceId;

    /**
     * @var string
     */
    private $merchantKey;

    /**
     * @var int
     */
    private $status;

    /**
     * @var string
     */
    private $hashKey;

    /**
     * @var int
     */
    private $total;

    /**
     * @param string $invoiceId
     * @param string $merchantKey
     * @param int $status
     * @param string $hashKey
     * @param int $total
     */
    public function __construct(string $invoiceId, string $merchantKey, int $status, string $hashKey, int $total)
    {
        $this->invoiceId = $invoiceId;
        $this->merchantKey = $merchantKey;
        $this->status = $status;
        $this->hashKey = $hashKey;
        $this->total = $total;
    }

    /**
     * Returns Invoice Id.
     */
    public function getInvoiceId(): string
    {
        return $this->invoiceId;
    }

    /**
     * Sets Invoice Id.
     *
     * @required
     * @maps invoice_id
     */
    public function setInvoiceId(string $invoiceId): void
    {
        $this->invoiceId = $invoiceId;
    }

    /**
     * Returns Merchant Key.
     */
    public function getMerchantKey(): string
    {
        return $this->merchantKey;
    }

    /**
     * Sets Merchant Key.
     *
     * @required
     * @maps merchant_key
     */
    public function setMerchantKey(string $merchantKey): void
    {
        $this->merchantKey = $merchantKey;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Hash Key.
     */
    public function getHashKey(): string
    {
        return $this->hashKey;
    }

    /**
     * Sets Hash Key.
     *
     * @required
     * @maps hash_key
     */
    public function setHashKey(string $hashKey): void
    {
        $this->hashKey = $hashKey;
    }

    /**
     * Returns Total.
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     *
     * @required
     * @maps total
     */
    public function setTotal(int $total): void
    {
        $this->total = $total;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['invoice_id']   = $this->invoiceId;
        $json['merchant_key'] = $this->merchantKey;
        $json['status']       = $this->status;
        $json['hash_key']     = $this->hashKey;
        $json['total']        = $this->total;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
